// Generated by CoffeeScript 1.7.1
(function() {
  var Resource, Schema, db;

  db = require('mongoose');

  Schema = db.Schema;

  Resource = Schema({
    date: {
      type: Date,
      "default": new Date
    },
    res: [
      {
        file: String,
        date: Date,
        desc: String
      }
    ]
  });

  module.exports = Resource;

}).call(this);

//# sourceMappingURL=Resource.map
