// Generated by CoffeeScript 1.7.1
(function() {
  var ObjectId, Schema, User, db;

  db = require('mongoose');

  Schema = db.Schema;

  ObjectId = Schema.Types.ObjectId;

  User = Schema({
    id: Number,
    name: String,
    password: String,
    area: [
      {
        area: ObjectId,
        chr: ObjectId
      }
    ]
  });

  module.exports = User;

}).call(this);

//# sourceMappingURL=User.map
